export enum AppMode {
  TREE = 'TREE',
  SCATTER = 'SCATTER',
  FOCUS = 'FOCUS',
  TEXT = 'TEXT',
  LOVE = 'LOVE'
}

export enum GestureType {
  NONE = 'NONE',
  OPEN_HAND = 'OPEN_HAND',
  CLOSED_FIST = 'CLOSED_FIST',
  PINCH = 'PINCH',
  POINTING = 'POINTING',
  VICTORY = 'VICTORY',
  HEART = 'HEART'
}

export interface PhotoData {
  id: string;
  url: string;
  description?: string; // Generated by Gemini
  position: [number, number, number]; // Tree position
  scatterPosition: [number, number, number]; // Random position
}

export interface HandData {
  gesture: GestureType;
  x: number; // Normalized 0-1
  y: number; // Normalized 0-1
  pinchedId?: string | null;
}